name: Bug Report
description: Create a report to help us improve.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: bot_version
    attributes:
      label: Bot Version
      description: What version of the bot are you running?
      placeholder: DO NOT PUT LATEST ex. 0.0.1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: Also tell us, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
      value: "If applicable, add screenshots to help explain your problem."
    validations:
      required: true
  - type: textarea
    id: reproduce_steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true